//! The vault as the iOS AutoFill extension (`app.rowel.mobile.autofill`) reads
//! it: the active workspace's database, found in the App Group container the
//! app keeps it in, opened with the key the app enrolled for Face ID, and read
//! for the logins that belong to the site being filled — or used as the
//! passkey authenticator for it (iOS 17 and later).
//!
//! Swift does the platform half — the container path, the Face ID prompt, the
//! keychain read — and hands Rust plain strings and bytes. Everything that
//! decides where the vault is, how the key opens it, which logins match and
//! how a passkey is made or signs is `rowel_core`, the code the app itself
//! runs.
//!
//! ## Passkeys
//! iOS is the WebAuthn client here: it checks the relying party against the
//! calling app or page and writes `clientDataJSON` itself, and hands the
//! extension only its hash. So unlike the browser host (`browser::passkeys` in
//! the app), nothing here builds client data or checks an origin; the hash is
//! signed as given. User verification is the Face ID unlock the sheet already
//! did, and the user's say is the sheet — the row tapped for a sign-in, the
//! confirmation for a registration — so the core's `UserConsent` is only told
//! the answer (`Answered`).
//!
//! The Swift side is generated by UniFFI (`bindgen.sh`).

use std::fs;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use passkey_types::ctap2::{get_assertion, make_credential, Ctap2Error, StatusCode};
use passkey_types::webauthn::{
    PublicKeyCredentialDescriptor, PublicKeyCredentialParameters, PublicKeyCredentialType,
    PublicKeyCredentialUserEntity,
};
use rowel_core::crypto::{self, PayloadCipher, VaultKey};
use rowel_core::host::{host_matches, site_host};
use rowel_core::keychain::{self, GateMode};
use rowel_core::layout::{self, BIOMETRIC_FILE, DB_FILE, KDF_SIDECAR_FILE, WRAPPED_KEY_FILE};
use rowel_core::passkey::store::{SessionVault, Stored, VaultCredentialStore};
use rowel_core::passkey::{key, Authenticator, Ceremony, UserConsent};
use rowel_core::store::{EntryMeta, SqliteStore, StoreError, VaultStore};
use rowel_core::workspace::{dir_of, Registry, PRIMARY_ID};
use zeroize::Zeroizing;

/// ES256, the one algorithm the vault's keys are.
const ES256: i64 = -7;

uniffi::setup_scaffolding!();

/// Why the vault cannot be read. Each case is one thing the extension says.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum AutofillError {
    /// No vault in the container: Rowel was never set up on this device, or
    /// its data is still in the app's own sandbox (an App Group the build was
    /// not entitled to).
    #[error("there is no vault on this device")]
    NoVault,
    /// Nothing here is unlockable without the master password: Face ID unlock
    /// is off, or the active workspace has no key sealed under the app key.
    #[error("unlock with Face ID is not turned on for this vault")]
    Locked,
    /// The key read from the keychain does not open the vault.
    #[error("the Face ID key does not open this vault")]
    WrongKey,
    /// No login under that record: deleted, or of another workspace. For a
    /// passkey sign-in, no passkey for the site that the request admits (and
    /// the record names, when it names one): iOS's `credentialIdentityNotFound`.
    #[error("no such login")]
    NotFound,
    /// A passkey sign-in with several accounts to be and none picked: the
    /// sheet lists them rather than asking with no record.
    #[error("no account was picked")]
    Denied,
    /// The registration's exclude list names a passkey this vault holds: the
    /// account already has one here, and a second is not made.
    #[error("Rowel already has a passkey for this account")]
    Excluded,
    /// The relying party takes no ES256 key, the one kind the vault makes.
    #[error("this site does not accept the kind of passkey Rowel makes")]
    Unsupported,
    #[error("{message}")]
    Io { message: String },
}

impl From<StoreError> for AutofillError {
    fn from(e: StoreError) -> Self {
        match e {
            StoreError::WrongKey => Self::WrongKey,
            e => Self::Io {
                message: e.to_string(),
            },
        }
    }
}

impl From<rowel_core::error::Error> for AutofillError {
    fn from(e: rowel_core::error::Error) -> Self {
        Self::Io {
            message: e.to_string(),
        }
    }
}

/// The active vault's place, and the keychain item its key is in. Read
/// without the key: what Swift needs to know before it asks for Face ID.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct VaultLocation {
    /// The data dir: `<container>/app.rowel.mobile`, and its `dev` subdir in a
    /// debug build, as the app lays it out (`layout::app_group_root`).
    pub root: String,
    /// The active workspace, as the registry names it.
    pub workspace: String,
    /// The generic-password item holding the app key, in the App Group's
    /// keychain access group: the account is the one for the gate the app
    /// enrolled behind.
    pub keychain_service: String,
    pub keychain_account: String,
}

/// A login offered for the site, with nothing secret in it: a row's name, the
/// name it signs in with and its site. `record` is the credential identity's
/// `"<workspace id>/<entry id>"`, as the app publishes it to iOS.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Credential {
    pub record: String,
    pub title: String,
    pub user: String,
    pub host: String,
}

/// What a chosen login fills.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Password {
    pub user: String,
    pub password: String,
}

/// A passkey the vault holds for a relying party, named the way the site named
/// it at registration; nothing that signs. `record` is the login it is on, in
/// the form the app publishes it to iOS as an `ASPasskeyCredentialIdentity`'s
/// `recordIdentifier` — one login can carry several passkeys, so the
/// credential id is what names the passkey itself.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct PasskeyAccount {
    pub record: String,
    pub credential_id: Vec<u8>,
    pub user_name: String,
    pub user_display_name: String,
    /// RFC 3339, when the vault has it: what tells two same-named passkeys
    /// apart.
    pub created_at: Option<String>,
}

/// A registration, as iOS hands it over (`ASPasskeyCredentialRequest`).
#[derive(Debug, Clone, uniffi::Record)]
pub struct PasskeyRegistration {
    pub rp_id: String,
    pub rp_name: Option<String>,
    pub user_name: String,
    pub user_display_name: Option<String>,
    pub user_handle: Vec<u8>,
    /// The SHA-256 of the `clientDataJSON` iOS wrote.
    pub client_data_hash: Vec<u8>,
    pub excluded_credential_ids: Vec<Vec<u8>>,
    /// COSE algorithm identifiers the relying party takes; empty is any.
    pub supported_algorithms: Vec<i64>,
}

/// What `ASPasskeyRegistrationCredential` carries back besides what iOS sent.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct RegisteredPasskey {
    pub credential_id: Vec<u8>,
    /// CBOR, "none" attestation.
    pub attestation_object: Vec<u8>,
}

/// A sign-in, as iOS hands it over (`ASPasskeyCredentialRequestParameters` for
/// the list, `ASPasskeyCredentialRequest` for a QuickType identity), and the
/// account the user picked.
#[derive(Debug, Clone, uniffi::Record)]
pub struct PasskeyAssertion {
    pub rp_id: String,
    /// The SHA-256 of the `clientDataJSON` iOS wrote.
    pub client_data_hash: Vec<u8>,
    /// The ids the relying party allows; empty is any of the site's.
    pub allowed_credential_ids: Vec<Vec<u8>>,
    /// The login picked: a [`PasskeyAccount`]'s record, or a QuickType
    /// identity's `recordIdentifier`. With it, name the passkey itself by
    /// narrowing `allowed_credential_ids` to the one picked, since one login
    /// can carry several. With none, the site must leave exactly one account.
    pub record: Option<String>,
}

/// What `ASPasskeyAssertionCredential` carries back besides what iOS sent.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct AssertedPasskey {
    pub credential_id: Vec<u8>,
    pub user_handle: Vec<u8>,
    pub authenticator_data: Vec<u8>,
    /// DER-encoded ECDSA over `authenticator_data || client_data_hash`.
    pub signature: Vec<u8>,
}

/// The App Group the vault and the key are shared through — one spelling for
/// the Swift side as well (`rowel_core::app::APP_GROUP`).
#[uniffi::export]
pub fn app_group() -> String {
    rowel_core::app::APP_GROUP.to_string()
}

/// Where the active vault is in the App Group container at `container`, and
/// which keychain item opens it.
#[uniffi::export]
pub fn vault_location(container: String) -> Result<VaultLocation, AutofillError> {
    let root = layout::app_group_root(Path::new(&container));
    let workspace = Registry::load(&root).active;
    let dir = dir_of(&root, &workspace);
    if !has_database(&dir) {
        return Err(AutofillError::NoVault);
    }
    // The marker names the gate the key went in behind, and so the item's
    // account. No marker, no key.
    let marker =
        fs::read_to_string(root.join(BIOMETRIC_FILE)).map_err(|_| AutofillError::Locked)?;
    let keychain_account = match GateMode::from_marker(&marker) {
        GateMode::Protected => keychain::ACCOUNT,
        GateMode::Prompt => keychain::ACCOUNT_PROMPT,
        GateMode::HelloKey => return Err(AutofillError::Locked),
    };
    // The stored key is the app key, the primary's; any other workspace opens
    // through its own key sealed under it, and one without is not offered a
    // Face ID unlock by the app either.
    if workspace != PRIMARY_ID && !dir.join(WRAPPED_KEY_FILE).exists() {
        return Err(AutofillError::Locked);
    }
    Ok(VaultLocation {
        root: root.to_string_lossy().into_owned(),
        workspace,
        keychain_service: keychain::SERVICE.to_string(),
        keychain_account: keychain_account.to_string(),
    })
}

/// Open the vault at `location` with `key`, the bytes of its keychain item.
#[uniffi::export]
pub fn open_vault(location: VaultLocation, key: Vec<u8>) -> Result<Arc<Vault>, AutofillError> {
    let dir = dir_of(&PathBuf::from(&location.root), &location.workspace);
    // `SqliteStore::open` makes a database where there is none; the extension
    // must never be what creates a vault.
    if !has_database(&dir) {
        return Err(AutofillError::NoVault);
    }
    let app_key = Zeroizing::new(key);
    let material = if location.workspace == PRIMARY_ID {
        app_key
    } else {
        let sealed =
            fs::read_to_string(dir.join(WRAPPED_KEY_FILE)).map_err(|e| match e.kind() {
                std::io::ErrorKind::NotFound => AutofillError::Locked,
                _ => AutofillError::Io {
                    message: e.to_string(),
                },
            })?;
        crypto::open_workspace_key(&app_key, &location.workspace, &sealed)
            .map_err(|_| AutofillError::WrongKey)?
    };
    // As the app reads the same bytes: an Argon2id master where there is a
    // KDF sidecar, the legacy secret where there is none.
    let key = VaultKey::from_material(material, dir.join(KDF_SIDECAR_FILE).exists());
    let store = SqliteStore::open(&dir.join(DB_FILE), key.sqlcipher_key().as_slice())?;
    Ok(Arc::new(Vault {
        workspace: location.workspace,
        store,
        cipher: key.payload_cipher(),
    }))
}

fn has_database(dir: &Path) -> bool {
    fs::metadata(dir.join(DB_FILE)).is_ok_and(|m| m.len() > 0)
}

/// An open vault. Lives as long as the extension's sheet.
#[derive(uniffi::Object)]
pub struct Vault {
    workspace: String,
    store: SqliteStore,
    cipher: PayloadCipher,
}

#[uniffi::export]
impl Vault {
    /// The logins for the sites iOS names: each identifier a domain or a URL,
    /// matched by the rule the browser extension fills by (`host_matches`) —
    /// the site itself or a parent of it, never across a public suffix. No
    /// identifiers is no site to go by, and every login is offered.
    ///
    /// Nothing is unsealed but the name a login signs in with, and that only
    /// for the rows whose listing does not carry one.
    pub fn credentials_for(
        &self,
        service_identifiers: Vec<String>,
    ) -> Result<Vec<Credential>, AutofillError> {
        let sites: Vec<String> = service_identifiers
            .iter()
            .filter_map(|id| service_host(id))
            .collect();
        let offered = |meta: &EntryMeta| {
            meta.kind == "login"
                && (service_identifiers.is_empty()
                    || sites.iter().any(|site| host_matches(site, &meta.url_host)))
        };
        Ok(self
            .store
            .list()?
            .into_iter()
            .filter(offered)
            .map(|meta| Credential {
                record: format!("{}/{}", self.workspace, meta.id),
                user: self.user_of(&meta),
                title: meta.title,
                host: meta.url_host,
            })
            .collect())
    }

    /// The name and password `record` fills, unsealing that row alone.
    pub fn password(&self, record: String) -> Result<Password, AutofillError> {
        let id = self.entry_of(&record)?;
        let row = self.store.get(id)?.ok_or(AutofillError::NotFound)?;
        if row.kind != "login" {
            return Err(AutofillError::NotFound);
        }
        let entry = self.cipher.unseal(&row.id, &row.payload)?;
        Ok(Password {
            user: entry.login_name().unwrap_or_default().to_string(),
            password: entry.password.clone().unwrap_or_default(),
        })
    }

    /// The passkeys for `rp_id` that `allowed_credential_ids` admits (none is
    /// all of them), newest first: the list the authenticator itself picks
    /// from, so what the sheet offers is what can sign.
    pub fn passkeys_for(
        &self,
        rp_id: String,
        allowed_credential_ids: Vec<Vec<u8>>,
    ) -> Result<Vec<PasskeyAccount>, AutofillError> {
        Ok(self
            .passkeys(&rp_id, &descriptors(&allowed_credential_ids))?
            .into_iter()
            .filter_map(|stored| {
                Some(PasskeyAccount {
                    credential_id: key::decode_credential_id(&stored.passkey.credential_id).ok()?,
                    record: format!("{}/{}", self.workspace, stored.entry_id),
                    user_name: stored.passkey.user_name,
                    user_display_name: stored.passkey.user_display_name,
                    created_at: stored.passkey.created_at,
                })
            })
            .collect())
    }

    /// Make a passkey for the site and keep it: on the site's one login when
    /// it has exactly one, on a new login otherwise, as on the desktop. The
    /// user said yes on the sheet before this is called.
    ///
    /// iOS only learns of the passkey for QuickType when the app next runs and
    /// publishes its identities; until then the sheet's list offers it.
    pub fn register_passkey(
        &self,
        request: PasskeyRegistration,
    ) -> Result<RegisteredPasskey, AutofillError> {
        let algorithms = &request.supported_algorithms;
        if !algorithms.is_empty() && !algorithms.contains(&ES256) {
            return Err(AutofillError::Unsupported);
        }
        let exclude = descriptors(&request.excluded_credential_ids);
        let request = make_credential::Request {
            client_data_hash: request.client_data_hash.into(),
            rp: make_credential::PublicKeyCredentialRpEntity {
                id: request.rp_id,
                name: request.rp_name,
            },
            user: PublicKeyCredentialUserEntity {
                id: request.user_handle.into(),
                name: request.user_name,
                display_name: request.user_display_name.unwrap_or_default(),
            },
            pub_key_cred_params: vec![PublicKeyCredentialParameters {
                ty: PublicKeyCredentialType::PublicKey,
                alg: coset::iana::Algorithm::ES256,
            }],
            exclude_list: (!exclude.is_empty()).then_some(exclude),
            extensions: None,
            // As the browser host asks: every passkey here is discoverable
            // anyway, and verified by the unlock.
            options: make_credential::Options {
                rk: false,
                up: true,
                uv: true,
            },
            pin_auth: None,
            pin_protocol: None,
        };
        let created = run(self.authenticator(Answered::Yes).make_credential(request))?;
        let credential_id = created
            .auth_data
            .attested_credential_data
            .as_ref()
            .map(|attested| attested.credential_id().to_vec())
            .ok_or_else(|| io("the new passkey has no credential id"))?;
        Ok(RegisteredPasskey {
            credential_id,
            attestation_object: created.as_webauthn_bytes().to_vec(),
        })
    }

    /// Sign iOS's client data hash with the passkey picked. The account is
    /// resolved here, from the same list [`Self::passkeys_for`] gives, and
    /// the core is told the pick through its consent — so the core's own
    /// narrowing to that record is what signs.
    pub fn assert_passkey(
        &self,
        request: PasskeyAssertion,
    ) -> Result<AssertedPasskey, AutofillError> {
        let allow = descriptors(&request.allowed_credential_ids);
        let found = self.passkeys(&request.rp_id, &allow)?;
        let index = match &request.record {
            Some(record) => {
                let entry = self.entry_of(record)?;
                found.iter().position(|stored| stored.entry_id == entry)
            }
            None if found.len() == 1 => Some(0),
            None if found.is_empty() => None,
            None => return Err(AutofillError::Denied),
        }
        .ok_or(AutofillError::NotFound)?;
        let picked = Answered::Account {
            index,
            credential_id: found[index].passkey.credential_id.clone(),
        };
        let request = get_assertion::Request {
            rp_id: request.rp_id,
            client_data_hash: request.client_data_hash.into(),
            allow_list: (!allow.is_empty()).then_some(allow),
            extensions: None,
            options: get_assertion::Options {
                rk: false,
                up: true,
                uv: true,
            },
            pin_auth: None,
            pin_protocol: None,
        };
        let signed = run(self.authenticator(picked).get_assertion(request))?;
        Ok(AssertedPasskey {
            credential_id: signed
                .credential
                .map(|credential| credential.id.to_vec())
                .ok_or_else(|| io("the assertion names no credential"))?,
            user_handle: signed.user.map(|user| user.id.to_vec()).unwrap_or_default(),
            authenticator_data: signed.auth_data.to_vec(),
            signature: signed.signature.to_vec(),
        })
    }
}

impl Vault {
    // The record's entry id, when the record is this workspace's.
    fn entry_of<'a>(&self, record: &'a str) -> Result<&'a str, AutofillError> {
        record
            .split_once('/')
            .filter(|(workspace, _)| *workspace == self.workspace)
            .map(|(_, id)| id)
            .ok_or(AutofillError::NotFound)
    }

    fn authenticator(&self, consent: Answered) -> Authenticator<SessionVault<'_>> {
        Authenticator::new(SessionVault::new(&self.store, &self.cipher), consent)
    }

    // The core's own list of what could sign — `Authenticator::get_assertion`
    // offers the user exactly this — so an index into it is an index into
    // what the core asks about.
    fn passkeys(
        &self,
        rp_id: &str,
        allow: &[PublicKeyCredentialDescriptor],
    ) -> Result<Vec<Stored>, AutofillError> {
        VaultCredentialStore::new(
            SessionVault::new(&self.store, &self.cipher),
            Default::default(),
        )
        .matching((!allow.is_empty()).then_some(allow), rp_id)
        .map_err(ceremony_error)
    }

    // The name a login signs in with: the listing's username column, or —
    // when it has none, as a login that signs in with an email does not —
    // the payload's (`Entry::login_name`), the name the app publishes to
    // QuickType for the same row.
    fn user_of(&self, meta: &EntryMeta) -> String {
        if let Some(user) = meta.username.as_deref().filter(|u| !u.is_empty()) {
            return user.to_string();
        }
        self.store
            .get(&meta.id)
            .ok()
            .flatten()
            .and_then(|row| self.cipher.unseal(&row.id, &row.payload).ok())
            .and_then(|entry| entry.login_name().map(str::to_string))
            .unwrap_or_default()
    }
}

/// The user's answer, given on the sheet before a ceremony starts: the core
/// asks, and this repeats it. A registration's yes is the confirmation; a
/// sign-in's is the account picked, by its place in the list the core asks
/// with — and only while that place still holds the passkey picked.
enum Answered {
    Yes,
    Account { index: usize, credential_id: String },
}

impl UserConsent for Answered {
    fn approve(&self, ceremony: Ceremony<'_>) -> Option<usize> {
        match (self, ceremony) {
            (Self::Yes, Ceremony::Register { .. }) => Some(0),
            (
                Self::Account {
                    index,
                    credential_id,
                },
                Ceremony::SignIn { accounts, .. },
            ) => accounts
                .get(*index)
                .filter(|account| account.credential_id == *credential_id)
                .map(|_| *index),
            _ => None,
        }
    }
}

// The authenticator's traits are async, but nothing under them waits on
// anything: the answer is in before a ceremony starts. A current-thread
// runtime is all the driving it needs.
fn run<T>(ceremony: impl Future<Output = Result<T, StatusCode>>) -> Result<T, AutofillError> {
    tokio::runtime::Builder::new_current_thread()
        .build()
        .map_err(|e| io(e.to_string()))?
        .block_on(ceremony)
        .map_err(ceremony_error)
}

// The CTAP status a ceremony ends with, as the one thing the extension does
// about it. The vault's own failures are logged by the core and arrive as the
// catch-all.
fn ceremony_error(status: StatusCode) -> AutofillError {
    let is = |error: Ctap2Error| status == StatusCode::from(error);
    if is(Ctap2Error::NoCredentials) {
        AutofillError::NotFound
    } else if is(Ctap2Error::OperationDenied) {
        AutofillError::Denied
    } else if is(Ctap2Error::CredentialExcluded) {
        AutofillError::Excluded
    } else if is(Ctap2Error::UnsupportedAlgorithm) {
        AutofillError::Unsupported
    } else {
        io(format!("the passkey could not be used ({status:?})"))
    }
}

fn io(message: impl Into<String>) -> AutofillError {
    AutofillError::Io {
        message: message.into(),
    }
}

fn descriptors(ids: &[Vec<u8>]) -> Vec<PublicKeyCredentialDescriptor> {
    ids.iter()
        .map(|id| PublicKeyCredentialDescriptor {
            ty: PublicKeyCredentialType::PublicKey,
            id: id.clone().into(),
            transports: None,
        })
        .collect()
}

// The host a service identifier names: iOS passes a URL for a web page and a
// bare domain for an app's associated domain, and both read here the way a
// browser's page does for the browser host.
fn service_host(identifier: &str) -> Option<String> {
    let identifier = identifier.trim();
    if identifier.is_empty() {
        return None;
    }
    site_host(identifier).or_else(|| site_host(&format!("https://{identifier}")))
}

#[cfg(test)]
mod tests;
