//! The vault as the iOS AutoFill extension (`app.rowel.mobile.autofill`) reads
//! it: the active workspace's database, found in the App Group container the
//! app keeps it in, opened with the key the app enrolled for Face ID, and read
//! for the logins that belong to the site being filled.
//!
//! Swift does the platform half — the container path, the Face ID prompt, the
//! keychain read — and hands Rust plain strings and bytes. Everything that
//! decides where the vault is, how the key opens it and which logins match is
//! `rowel_core`, the code the app itself runs.
//!
//! The Swift side is generated by UniFFI (`bindgen.sh`).

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use rowel_core::crypto::{self, PayloadCipher, VaultKey};
use rowel_core::host::{host_matches, site_host};
use rowel_core::keychain::{self, GateMode};
use rowel_core::layout::{self, BIOMETRIC_FILE, DB_FILE, KDF_SIDECAR_FILE, WRAPPED_KEY_FILE};
use rowel_core::store::{EntryMeta, SqliteStore, StoreError, VaultStore};
use rowel_core::workspace::{dir_of, Registry, PRIMARY_ID};
use zeroize::Zeroizing;

uniffi::setup_scaffolding!();

/// Why the vault cannot be read. Each case is one thing the extension says.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum AutofillError {
    /// No vault in the container: Rowel was never set up on this device, or
    /// its data is still in the app's own sandbox (an App Group the build was
    /// not entitled to).
    #[error("there is no vault on this device")]
    NoVault,
    /// Nothing here is unlockable without the master password: Face ID unlock
    /// is off, or the active workspace has no key sealed under the app key.
    #[error("unlock with Face ID is not turned on for this vault")]
    Locked,
    /// The key read from the keychain does not open the vault.
    #[error("the Face ID key does not open this vault")]
    WrongKey,
    /// No login under that record: deleted, or of another workspace.
    #[error("no such login")]
    NotFound,
    #[error("{message}")]
    Io { message: String },
}

impl From<StoreError> for AutofillError {
    fn from(e: StoreError) -> Self {
        match e {
            StoreError::WrongKey => Self::WrongKey,
            e => Self::Io {
                message: e.to_string(),
            },
        }
    }
}

impl From<rowel_core::error::Error> for AutofillError {
    fn from(e: rowel_core::error::Error) -> Self {
        Self::Io {
            message: e.to_string(),
        }
    }
}

/// The active vault's place, and the keychain item its key is in. Read
/// without the key: what Swift needs to know before it asks for Face ID.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct VaultLocation {
    /// The data dir: `<container>/app.rowel.mobile`, and its `dev` subdir in a
    /// debug build, as the app lays it out (`layout::app_group_root`).
    pub root: String,
    /// The active workspace, as the registry names it.
    pub workspace: String,
    /// The generic-password item holding the app key, in the App Group's
    /// keychain access group: the account is the one for the gate the app
    /// enrolled behind.
    pub keychain_service: String,
    pub keychain_account: String,
}

/// A login offered for the site, with nothing secret in it: a row's name, the
/// name it signs in with and its site. `record` is the credential identity's
/// `"<workspace id>/<entry id>"`, as the app publishes it to iOS.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Credential {
    pub record: String,
    pub title: String,
    pub user: String,
    pub host: String,
}

/// What a chosen login fills.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Password {
    pub user: String,
    pub password: String,
}

/// The App Group the vault and the key are shared through — one spelling for
/// the Swift side as well (`rowel_core::app::APP_GROUP`).
#[uniffi::export]
pub fn app_group() -> String {
    rowel_core::app::APP_GROUP.to_string()
}

/// Where the active vault is in the App Group container at `container`, and
/// which keychain item opens it.
#[uniffi::export]
pub fn vault_location(container: String) -> Result<VaultLocation, AutofillError> {
    let root = layout::app_group_root(Path::new(&container));
    let workspace = Registry::load(&root).active;
    let dir = dir_of(&root, &workspace);
    if !has_database(&dir) {
        return Err(AutofillError::NoVault);
    }
    // The marker names the gate the key went in behind, and so the item's
    // account. No marker, no key.
    let marker =
        fs::read_to_string(root.join(BIOMETRIC_FILE)).map_err(|_| AutofillError::Locked)?;
    let keychain_account = match GateMode::from_marker(&marker) {
        GateMode::Protected => keychain::ACCOUNT,
        GateMode::Prompt => keychain::ACCOUNT_PROMPT,
        GateMode::HelloKey => return Err(AutofillError::Locked),
    };
    // The stored key is the app key, the primary's; any other workspace opens
    // through its own key sealed under it, and one without is not offered a
    // Face ID unlock by the app either.
    if workspace != PRIMARY_ID && !dir.join(WRAPPED_KEY_FILE).exists() {
        return Err(AutofillError::Locked);
    }
    Ok(VaultLocation {
        root: root.to_string_lossy().into_owned(),
        workspace,
        keychain_service: keychain::SERVICE.to_string(),
        keychain_account: keychain_account.to_string(),
    })
}

/// Open the vault at `location` with `key`, the bytes of its keychain item.
#[uniffi::export]
pub fn open_vault(location: VaultLocation, key: Vec<u8>) -> Result<Arc<Vault>, AutofillError> {
    let dir = dir_of(&PathBuf::from(&location.root), &location.workspace);
    // `SqliteStore::open` makes a database where there is none; the extension
    // must never be what creates a vault.
    if !has_database(&dir) {
        return Err(AutofillError::NoVault);
    }
    let app_key = Zeroizing::new(key);
    let material = if location.workspace == PRIMARY_ID {
        app_key
    } else {
        let sealed =
            fs::read_to_string(dir.join(WRAPPED_KEY_FILE)).map_err(|e| match e.kind() {
                std::io::ErrorKind::NotFound => AutofillError::Locked,
                _ => AutofillError::Io {
                    message: e.to_string(),
                },
            })?;
        crypto::open_workspace_key(&app_key, &location.workspace, &sealed)
            .map_err(|_| AutofillError::WrongKey)?
    };
    // As the app reads the same bytes: an Argon2id master where there is a
    // KDF sidecar, the legacy secret where there is none.
    let key = VaultKey::from_material(material, dir.join(KDF_SIDECAR_FILE).exists());
    let store = SqliteStore::open(&dir.join(DB_FILE), key.sqlcipher_key().as_slice())?;
    Ok(Arc::new(Vault {
        workspace: location.workspace,
        store,
        cipher: key.payload_cipher(),
    }))
}

fn has_database(dir: &Path) -> bool {
    fs::metadata(dir.join(DB_FILE)).is_ok_and(|m| m.len() > 0)
}

/// An open vault. Lives as long as the extension's sheet.
#[derive(uniffi::Object)]
pub struct Vault {
    workspace: String,
    store: SqliteStore,
    cipher: PayloadCipher,
}

#[uniffi::export]
impl Vault {
    /// The logins for the sites iOS names: each identifier a domain or a URL,
    /// matched by the rule the browser extension fills by (`host_matches`) —
    /// the site itself or a parent of it, never across a public suffix. No
    /// identifiers is no site to go by, and every login is offered.
    ///
    /// Nothing is unsealed but the name a login signs in with, and that only
    /// for the rows whose listing does not carry one.
    pub fn credentials_for(
        &self,
        service_identifiers: Vec<String>,
    ) -> Result<Vec<Credential>, AutofillError> {
        let sites: Vec<String> = service_identifiers
            .iter()
            .filter_map(|id| service_host(id))
            .collect();
        let offered = |meta: &EntryMeta| {
            meta.kind == "login"
                && (service_identifiers.is_empty()
                    || sites.iter().any(|site| host_matches(site, &meta.url_host)))
        };
        Ok(self
            .store
            .list()?
            .into_iter()
            .filter(offered)
            .map(|meta| Credential {
                record: format!("{}/{}", self.workspace, meta.id),
                user: self.user_of(&meta),
                title: meta.title,
                host: meta.url_host,
            })
            .collect())
    }

    /// The name and password `record` fills, unsealing that row alone.
    pub fn password(&self, record: String) -> Result<Password, AutofillError> {
        let id = record
            .split_once('/')
            .filter(|(workspace, _)| *workspace == self.workspace)
            .map(|(_, id)| id)
            .ok_or(AutofillError::NotFound)?;
        let row = self.store.get(id)?.ok_or(AutofillError::NotFound)?;
        if row.kind != "login" {
            return Err(AutofillError::NotFound);
        }
        let entry = self.cipher.unseal(&row.id, &row.payload)?;
        Ok(Password {
            user: entry.login_name().unwrap_or_default().to_string(),
            password: entry.password.clone().unwrap_or_default(),
        })
    }
}

impl Vault {
    // The name a login signs in with: the listing's username column, or —
    // when it has none, as a login that signs in with an email does not —
    // the payload's (`Entry::login_name`), the name the app publishes to
    // QuickType for the same row.
    fn user_of(&self, meta: &EntryMeta) -> String {
        if let Some(user) = meta.username.as_deref().filter(|u| !u.is_empty()) {
            return user.to_string();
        }
        self.store
            .get(&meta.id)
            .ok()
            .flatten()
            .and_then(|row| self.cipher.unseal(&row.id, &row.payload).ok())
            .and_then(|entry| entry.login_name().map(str::to_string))
            .unwrap_or_default()
    }
}

// The host a service identifier names: iOS passes a URL for a web page and a
// bare domain for an app's associated domain, and both read here the way a
// browser's page does for the browser host.
fn service_host(identifier: &str) -> Option<String> {
    let identifier = identifier.trim();
    if identifier.is_empty() {
        return None;
    }
    site_host(identifier).or_else(|| site_host(&format!("https://{identifier}")))
}

#[cfg(test)]
mod tests;
