#!/usr/bin/env node
// Reference implementation of the legacy @swiftyapp/cryptor vault format, using
// only Node's built-in `crypto`. Mirrors legacy/src/main/application/cryptor/index.js.
// Used to generate golden fixtures and to cross-check the Rust implementation.
//
// Format: hex( salt[64] ‖ iv[16] ‖ tag[16] ‖ ciphertext ), AES-256-GCM,
// key = PBKDF2-HMAC-SHA512(secret, salt, 100000, 32). Whole-object blobs are
// base64(hex). Secret = base64(SHA512(password)).

import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SALT_LEN = 64
const IV_LEN = 16
const TAG_LEN = 16
const ITERATIONS = 100000
const KEY_LEN = 32

const SENSITIVE_FIELDS = {
  login: ['password', 'otp'],
  note: ['note'],
  card: ['pin']
}

export const hashSecret = value =>
  crypto.createHash('sha512').update(value).digest('base64')

export class Cryptor {
  constructor(secret) {
    this.secret = secret
  }

  encrypt(data) {
    const salt = crypto.randomBytes(SALT_LEN)
    const iv = crypto.randomBytes(IV_LEN)
    const key = crypto.pbkdf2Sync(this.secret, salt, ITERATIONS, KEY_LEN, 'sha512')
    const cipher = crypto.createCipheriv('aes-256-gcm', key, iv)
    const ciphertext = Buffer.concat([cipher.update(data, 'utf8'), cipher.final()])
    const tag = cipher.getAuthTag()
    return Buffer.concat([salt, iv, tag, ciphertext]).toString('hex')
  }

  decrypt(data) {
    const buf = Buffer.from(data, 'hex')
    const salt = buf.subarray(0, SALT_LEN)
    const iv = buf.subarray(SALT_LEN, SALT_LEN + IV_LEN)
    const tag = buf.subarray(SALT_LEN + IV_LEN, SALT_LEN + IV_LEN + TAG_LEN)
    const ciphertext = buf.subarray(SALT_LEN + IV_LEN + TAG_LEN)
    const key = crypto.pbkdf2Sync(this.secret, salt, ITERATIONS, KEY_LEN, 'sha512')
    const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv)
    decipher.setAuthTag(tag)
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf8')
  }

  encryptData(data) {
    return Buffer.from(this.encrypt(JSON.stringify(data)), 'utf8').toString('base64')
  }

  decryptData(encrypted) {
    return JSON.parse(this.decrypt(Buffer.from(encrypted, 'base64').toString('utf8')))
  }

  #prepare(entry, callback) {
    const object = Object.assign({}, entry)
    ;(SENSITIVE_FIELDS[object.type] || []).forEach(field => {
      object[field] = !object[field] ? '' : callback(object[field])
    })
    return object
  }

  obscure(entry) {
    return this.#prepare(entry, v => this.encrypt(v))
  }

  expose(entry) {
    return this.#prepare(entry, v => this.decrypt(v))
  }
}

// ---- Golden fixture generation -------------------------------------------

const PASSWORD = 'correct horse battery staple'
const SECRET = hashSecret(PASSWORD)

const ENTRIES = [
  {
    id: '1',
    type: 'login',
    title: 'GitHub',
    username: 'octocat',
    password: 's3cr3t-p@ss',
    otp: 'JBSWY3DPEHPK3PXP',
    website: 'https://github.com'
  },
  {
    id: '2',
    type: 'login',
    title: 'No OTP',
    username: 'user',
    password: 'pw-only',
    otp: ''
  },
  {
    id: '3',
    type: 'login',
    title: 'Empty password',
    username: 'ghost',
    password: ''
  },
  { id: '4', type: 'note', title: 'Recovery', note: 'line one\nline two — dash' },
  { id: '5', type: 'note', title: 'Empty note', note: '' },
  {
    id: '6',
    type: 'card',
    title: 'Visa',
    number: '4111111111111111',
    month: '12',
    year: '2030',
    cvc: '123',
    pin: '4242'
  },
  { id: '7', type: 'card', title: 'No PIN', number: '5555555555554444', pin: '' },
  {
    id: '8',
    type: 'login',
    title: 'Unicode 🔐 Ключ 密码',
    username: 'iván',
    password: 'пароль-密码-🔑',
    otp: 'ünïcödé'
  },
  {
    id: '9',
    type: 'note',
    title: 'Long',
    note: 'x'.repeat(5000)
  }
]

function generateFixtures() {
  const c = new Cryptor(SECRET)

  const encrypt = ['s3cr3t-p@ss', 'пароль-密码-🔑', 'y'.repeat(4096)].map(
    (plaintext, i) => ({ name: `field-${i}`, plaintext, hex: c.encrypt(plaintext) })
  )

  const encryptData = [
    { name: 'empty-vault', value: { entries: [] } },
    { name: 'nested', value: { a: 1, b: 'два', c: [true, null, 'x'] } }
  ].map(({ name, value }) => ({ name, value, blob: c.encryptData(value) }))

  const obscured = ENTRIES.map(e => c.obscure(e))
  const exposed = obscured.map(e => c.expose(e))
  const vault = {
    name: 'full-vault',
    entries: ENTRIES,
    exposed,
    blob: c.encryptData({ entries: obscured })
  }

  return {
    note: 'Golden fixtures generated by scripts/crypto-ref.mjs. Regenerate with `node scripts/crypto-ref.mjs gen-fixtures`.',
    secret: SECRET,
    hashSecret: [{ password: PASSWORD, secret: SECRET }],
    encrypt,
    encryptData,
    vault
  }
}

// ---- CLI ------------------------------------------------------------------

function main() {
  const [cmd, ...args] = process.argv.slice(2)
  switch (cmd) {
    case 'hash-secret':
      process.stdout.write(hashSecret(args[0]))
      break
    case 'encrypt':
      process.stdout.write(new Cryptor(args[0]).encrypt(args[1]))
      break
    case 'decrypt':
      process.stdout.write(new Cryptor(args[0]).decrypt(args[1]))
      break
    case 'encrypt-data':
      process.stdout.write(new Cryptor(args[0]).encryptData(JSON.parse(args[1])))
      break
    case 'decrypt-data':
      process.stdout.write(JSON.stringify(new Cryptor(args[0]).decryptData(args[1])))
      break
    case 'gen-fixtures': {
      const __dirname = path.dirname(fileURLToPath(import.meta.url))
      const out = path.resolve(__dirname, '../src-tauri/tests/fixtures/fixtures.json')
      fs.mkdirSync(path.dirname(out), { recursive: true })
      fs.writeFileSync(out, JSON.stringify(generateFixtures(), null, 2) + '\n')
      process.stdout.write(`wrote ${out}\n`)
      break
    }
    default:
      process.stderr.write(
        'usage: crypto-ref.mjs <hash-secret|encrypt|decrypt|encrypt-data|decrypt-data|gen-fixtures> [args]\n'
      )
      process.exit(1)
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main()
}
